### ISSUE TITLE
Document Sets - Manage Sets

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#3615]
### Tasks 

- [x] Create named "set"
- [ ] Administration section for sets
- [x] List sets in "Manage Sets" administration page
