### ISSUE TITLE
Document Sets - Sets Configuration

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#3637]
### Tasks

- [x] Configure max number of sets per type
- [x] Configure max number of items per set
- [x] Configure "Create Sets" action (anonymous users vs authenticated users)
